GET http://localhost:3000/user
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjQyZDIwNTU1LTg0ZjAtNGYxNC1iMTJmLTBhYzcxNjFlODA4NyIsImVtYWlsIjoiam9obnNtaXRoQGV4YW1wbGUuY29tIiwiaWF0IjoxNjk2ODEzODYzfQ.V2A43vxLYwQt_k6E_0sFnffpjjTg8robANesDXYIuzA


###
GET http://localhost:3000/user/42d20555-84f0-4f14-b12f-0ac7161e8087


###
POST http://localhost:3000/user 
Content-Type: application/json

{
   "name":"Rodobaldo",
   "password":"12345",
   "rol":"user",
   "isActive":true,
   "email":"email@gmail.com"
}
###
PATCH  http://localhost:3000/user/42d20555-84f0-4f14-b12f-0ac7161e8087
Content-Type: application/json

{
   "name":"Rodobaldo",
   "password":"12345",
   "rol":"user",
   "isActive":true,
   "email":"email@gmail.com"
}